spring.application.name=cinemagateway

secret=7d98bbfd401ab922269f331e8f2305fd3634bb9ffeb31d702e962cb7627a672d

server.address=0.0.0.0
server.port=8080

services.users=http://user-service:8081
services.shows=http://show-service:8082
